In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/diabetic_data.csv')

In [5]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [8]:
df['max_glu_serum'] = df['max_glu_serum'].fillna('Not Tested')

In [9]:
df['A1Cresult'] = df['A1Cresult'].fillna('Not Tested')

In [10]:
df.isnull().sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [11]:
print((df == '?').sum())

encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [12]:
df = df.drop(columns = 'weight')

In [13]:
df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='str')

In [14]:
df['race'] = df['race'].replace('?', 'Unknown', regex = False)

In [15]:
df['payer_code'] = df['payer_code'].replace('?', 'Unknown', regex = False)

In [16]:
df['diag_1'] = df['diag_1'].replace('?', 'Unknown', regex = False)

In [17]:
df['diag_2'] = df['diag_2'].replace('?', 'Unknown', regex = False)

In [18]:
df['diag_3'] = df['diag_3'].replace('?', 'Unknown', regex = False)

In [19]:
print((df == '?').sum())

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [20]:
df['patient_nbr'].value_counts()

patient_nbr
88785891     40
43140906     28
1660293      23
23199021     23
88227540     23
             ..
183087545     1
188574944     1
140199494     1
120975314     1
175429310     1
Name: count, Length: 71518, dtype: int64

In [21]:
df.head(3)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,Unknown,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,Unknown,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,Unknown,...,No,No,No,No,No,No,No,No,Yes,NO

In [22]:
df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='str')

In [23]:
df[(df['time_in_hospital'] < 0) | (df['num_lab_procedures'] < 0) | (df['num_procedures'] < 0) | (df['num_medications'] < 0)
   | (df['number_outpatient'] < 0) | (df['number_emergency'] < 0) | (df['number_inpatient'] < 0) ].shape[0]

0

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   admission_type_id         101766 non-null  int64
 6   discharge_disposition_id  101766 non-null  int64
 7   admission_source_id       101766 non-null  int64
 8   time_in_hospital          101766 non-null  int64
 9   payer_code                101766 non-null  str
 10  medical_specialty         101766 non-null  str
 11  num_lab_procedures        101766 non-null  int64
 12  num_procedures            101766 non-null  int64
 13  num_medications           101766 non-null  int64
 14  number_outpatient         101766 non-null  int64
 15  number_emergency          101766 non-null  int64
 16  number_inpatient          101766 non-null  int64
 17  diag_1                    101766 non-null  str
 18  diag_2                    101766 non-null  str
 19  diag_3                    101766 non-null  str
 20  number_diagnoses          101766 non-null  int64
 21  max_glu_serum             101766 non-null  str
 22  A1Cresult                 101766 non-null  str
 23  metformin                 101766 non-null  str
 24  repaglinide               101766 non-null  str
 25  nateglinide               101766 non-null  str
 26  chlorpropamide            101766 non-null  str
 27  glimepiride               101766 non-null  str
 28  acetohexamide             101766 non-null  str
 29  glipizide                 101766 non-null  str
 30  glyburide                 101766 non-null  str
 31  tolbutamide               101766 non-null  str
 32  pioglitazone              101766 non-null  str
 33  rosiglitazone             101766 non-null  str
 34  acarbose                  101766 non-null  str
 35  miglitol                  101766 non-null  str
 36  troglitazone              101766 non-null  str
 37  tolazamide                101766 non-null  str
 38  examide                   101766 non-null  str
 39  citoglipton               101766 non-null  str
 40  insulin                   101766 non-null  str
 41  glyburide-metformin       101766 non-null  str
 42  glipizide-metformin       101766 non-null  str
 43  glimepiride-pioglitazone  101766 non-null  str
 44  metformin-rosiglitazone   101766 non-null  str
 45  metformin-pioglitazone    101766 non-null  str
 46  change                    101766 non-null  str
 47  diabetesMed               101766 non-null  str
 48  readmitted                101766 non-null  str
dtypes: int64(13), str(36)
memory usage: 38.0 MB

In [25]:
df['new_age'] = df['age'].str.replace(r'[\[\)]', '', regex = True)

In [26]:
df['new_age'].head()

0     0-10
1    10-20
2    20-30
3    30-40
4    40-50
Name: new_age, dtype: str

In [27]:
df['new_age'] = df['new_age'].str.split('-').apply(lambda x: (int(x[0]) + int(x[1]))/2 )

In [28]:
df['new_age'].head()

0     5.0
1    15.0
2    25.0
3    35.0
4    45.0
Name: new_age, dtype: float64

In [29]:
df['new_age'] = df['new_age'].astype(int)

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   admission_type_id         101766 non-null  int64
 6   discharge_disposition_id  101766 non-null  int64
 7   admission_source_id       101766 non-null  int64
 8   time_in_hospital          101766 non-null  int64
 9   payer_code                101766 non-null  str
 10  medical_specialty         101766 non-null  str
 11  num_lab_procedures        101766 non-null  int64
 12  num_procedures            101766 non-null  int64
 13  num_medications           101766 non-null  int64
 14  number_outpatient         101766 non-null  int64
 15  number_emergency          101766 non-null  int64
 16  number_inpatient          101766 non-null  int64
 17  diag_1                    101766 non-null  str
 18  diag_2                    101766 non-null  str
 19  diag_3                    101766 non-null  str
 20  number_diagnoses          101766 non-null  int64
 21  max_glu_serum             101766 non-null  str
 22  A1Cresult                 101766 non-null  str
 23  metformin                 101766 non-null  str
 24  repaglinide               101766 non-null  str
 25  nateglinide               101766 non-null  str
 26  chlorpropamide            101766 non-null  str
 27  glimepiride               101766 non-null  str
 28  acetohexamide             101766 non-null  str
 29  glipizide                 101766 non-null  str
 30  glyburide                 101766 non-null  str
 31  tolbutamide               101766 non-null  str
 32  pioglitazone              101766 non-null  str
 33  rosiglitazone             101766 non-null  str
 34  acarbose                  101766 non-null  str
 35  miglitol                  101766 non-null  str
 36  troglitazone              101766 non-null  str
 37  tolazamide                101766 non-null  str
 38  examide                   101766 non-null  str
 39  citoglipton               101766 non-null  str
 40  insulin                   101766 non-null  str
 41  glyburide-metformin       101766 non-null  str
 42  glipizide-metformin       101766 non-null  str
 43  glimepiride-pioglitazone  101766 non-null  str
 44  metformin-rosiglitazone   101766 non-null  str
 45  metformin-pioglitazone    101766 non-null  str
 46  change                    101766 non-null  str
 47  diabetesMed               101766 non-null  str
 48  readmitted                101766 non-null  str
 49  new_age                   101766 non-null  int64
dtypes: int64(14), str(36)
memory usage: 38.8 MB

In [31]:
pd.set_option('display.max_columns', None)
df.head()

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,new_age
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,Unknown,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,Unknown,Unknown,1,Not Tested,Not Tested,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,5
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,Unknown,?,59,0,18,0,0,0,276,250.01,255,9,Not Tested,Not Tested,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,15
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,Unknown,?,11,5,13,2,0,1,648,250,V27,6,Not Tested,Not Tested,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,25
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,Unknown,?,44,1,16,0,0,0,8,250.43,403,7,Not Tested,Not Tested,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,35
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,Unknown,?,51,0,8,0,0,0,197,157,250,5,Not Tested,Not Tested,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,45

In [32]:
pd.reset_option('display.max_columns')

In [33]:
df['time_in_hospital'].max()

np.int64(14)

In [34]:
df['time_in_hospital'].min()

np.int64(1)

In [35]:
df['readmitted'].value_counts()

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [36]:
df[(df['time_in_hospital'] < 1) | (df['time_in_hospital'] > 14)].shape[0]

0

In [37]:
df['encounter_id'].duplicated().sum()

np.int64(0)

In [38]:
df.to_csv('../data/diabetic_data_cleaned.csv', index = False)